// 08-react/08-redux/04-todolis初始渲染和删除/src/components/AddTodo.jsx
import React, {Component} from 'react'

export default class AddTodo extends Component{
    constructor(props) {
        super(props);
    }
    render() {
        return (
            <div className="todo-header">
                <input
                    type="text"
                    placeholder="请输入今天的任务清单，按回车键确认"
                />
            </div>
        )
    }
}

// 05-vue/vuex/02-todomvc-vuex/src/components/AddTodo.vue
<template>
  <header class="header">
    <h1>目标</h1>
    <input
        v-model.trim="txt"
        type="text"
        placeholder="需要做什么?" class="new-todo"
        @keyup.enter="add"
    >
  </header>
</template>

<script>
import {mapGetters, mapMutations} from "vuex";

export default {
  name: "AddTodo",
  data() {
    return{
      txt:""
    }
  },
  methods:{
    ...mapMutations(["addTodo"]),
    add(){
      this.addTodo(this.txt);
      this.txt = "";
    },

  },
}
</script>

<style scoped>

</style>
