// vue/vue-cli/todomvc/src/components/AddTodo.vue
<template>
  <header class="header">
    <h1>todos</h1>
    <input
        type="text"
        placeholder="what need to be done?"
        class="new-todo"
        v-model="text"
        @keyup.enter="add"
    >
  </header>
</template>

<script>
export default {
  name: "AddTodo",
  data(){
    return{
      text:""
    }
  },
  methods:{
    add(){
      this.$emit("addTodo",{text:this.text,done:false})
      this.text = "";
    }
  }
}
</script>

// 08-react/04-todomvc/src/components/AddTodo/AddTodo.jsx
import React, {Component} from 'react';

class AddTodo extends Component {
    render() {
        return (
            <header className="header">
                <h1>todos</h1>
                <input type="text" placeholder="what need to be done?" className="new-todo" />
            </header>
        );
    }
}

export default AddTodo;
