// 08-react/08-redux/04-todolis初始渲染和删除/src/components/AddTodo.jsx
import React, {Component} from 'react'

export default class AddTodo extends Component{
    constructor(props) {
        super(props);
    }
    render() {
        return (
            <div className="todo-header">
                <input
                    type="text"
                    placeholder="请输入今天的任务清单，按回车键确认"
                />
            </div>
        )
    }
}

// vue/vue-cli/todomvc/src/components/AddTodo.vue
<template>
  <header class="header">
    <h1>todos</h1>
    <input
        type="text"
        placeholder="what need to be done?"
        class="new-todo"
        v-model="text"
        @keyup.enter="add"
    >
  </header>
</template>

<script>
export default {
  name: "AddTodo",
  data(){
    return{
      text:""
    }
  },
  methods:{
    add(){
      this.$emit("addTodo",{text:this.text,done:false})
      this.text = "";
    }
  }
}
</script>
